/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "btqgfxcwozgdqprdgynb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cWdmeGN3b3pnZHFwcmRneW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3NDMxOTAsImV4cCI6MjA4MzMxOTE5MH0.IVGrn-Ljw9er-ahDdOJJ46UHzGzYWAgePDlCmLoayaQ"